INSERT IGNORE INTO parties (party_name) VALUES
('PAP'),
('WP'),
('PSP'),
('SDP');

INSERT IGNORE INTO constituencies (year, name, type) VALUES
(2020, 'PIONEER', 'GRC'),
(2020, 'ANG MO KIO', 'GRC');

-- Password hashes will be generated by backend script later
INSERT IGNORE INTO users (username, password_hash, role_name, area) VALUES
('diana', 'REPLACE_ME', 'civilian', 'PIONEER'),
('eve', 'REPLACE_ME', 'government', 'ANG MO KIO');
